$('.owl-carousel').owlCarousel({
    loop:true,
    margin:8,
    nav:true,
    responsive:{
        0:{
            items:1
        },
        200:{
            items:3
        },
        600:{
            items:5
        }
    }
})